### PR TITLE
readme improvements

### LINKED ISSUE #5: Add a readme to show how to run the app

### PR DESCRIPTION
**Pull request by xnetcat**
closes #5

### CODE REVIEW

**Review by pradipta — APPROVED** [review]

**Review by pradipta — CHANGES_REQUESTED** [review]
Can you also make to and cc email configurable. With this, now all test emails would go to the to and cc mentioned in the code base.

**Comment by xnetcat** [comment]
sure give me a sec

**Comment by xnetcat** [comment]
@pradipta take a look 9ecc114

**Review by pradipta — APPROVED** [review]
LGTM.

**Review by first-brick — APPROVED** [review]

**Pull request merged**
